project:
  type: website

website:
  title: "blog-quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
theme:
  light: cosmo
  dark: darkly
format:
  html:
    theme: cosmo
    css: styles.css



